apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  type: ClusterIP       
  ports:
  - name: http
    port: 3000
    targetPort: http
  externalIPs: ["192.168.56.101"]
  sessionAffinity: ClientIP
  selector:
    app: grafana

