apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 9100
    targetPort: https
  externalIPs: ["192.168.56.101"] 
  selector:
    app: node-exporter
