apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: monitoring 
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /mnt/sharedfolder
    server: 192.168.56.101
  persistentVolumeReclaimPolicy: Retain
