apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim1
  namespace: monitoring
spec:
  storageClassName: manual      
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi 
